import { Inter } from "next/font/google";
import LandingPage from "../../components/LandingPage";
import '../../styles/globals.css'
import Outerbody from "../../components/Outerbody"


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        {/* <LandingPage /> */}
        <Outerbody />
      </body>
    </html>
  );
}
